exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprctl setcursor capitaine-cursors 24
exec-once = awww-daemon && sleep 1 && awww img ~/Wallpapers/nebula_purple.png
exec-once = waybar
exec-once = qs -c overview
exec-once = swaync
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = xdg-desktop-portal-hyprland
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = eval $(ssh-agent)
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
