general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd =
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
