windowrule = float class:^(Rofi)$
windowrule = center class:^(Rofi)$
windowrule = float class:^(wlogout)$
windowrule = center class:^(wlogout)$
windowrule = float class:^(pavucontrol)$
windowrule = float class:^(swaync)$
windowrule = center class:^(pavucontrol)$
windowrule = float class:^(wallpicker)$
windowrule = fullscreen class:^(wallpicker)$
windowrule = center class:^(wallpicker)$
windowrule = float class:^(mpv|vlc|ffplay|celluloid)$
windowrule = float class:^(feh|imv|pinta|gwenview|loupe)$
windowrule = float class:^(galculator|gnome-calculator|qalculate-gtk)$
windowrule = float class:^(xdg-desktop-portal|xdg-desktop-portal-hyprland)$
windowrule = float class:^(blueman-manager|blueman-adapters)$
windowrule = float class:^(qt5ct|qt6ct)$
windowrule = float class:^(pamac-manager|octopi)$
windowrule = float class:^(org.gnome.Nautilus)$
